doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    default_database: '%env(resolve:MONGODB_DB)%'
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options:
                username: '%env(resolve:MONGODB_USERNAME)%'
                password: '%env(resolve:MONGODB_PASSWORD)%'

    document_managers:
        default:
            connection: default
            database: '%env(resolve:MONGODB_DB)%'
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App

when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system
