twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        limit_pages: [10,25,50,100]
    form_themes:
        - 'bootstrap_4_layout.html.twig'

when@test:
    twig:
        strict_variables: true
